/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypter;

/**
 *
 * @author jakes_000
 */
public class EncrypterView extends javax.swing.JFrame {

    /**
     * Creates new form EncrypterView
     */
    public EncrypterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        encryptData = new javax.swing.JTextField();
        decryptData = new javax.swing.JTextField();
        encryptKey = new javax.swing.JTextField();
        decryptKey = new javax.swing.JTextField();
        encrypt = new javax.swing.JButton();
        decrypt = new javax.swing.JButton();
        dePass = new javax.swing.JTextField();
        enPass = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        social = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Input new user");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 11, 109, -1));

        jLabel2.setText("Output Info");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 11, 102, -1));

        encryptData.setText("Username");
        encryptData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptDataActionPerformed(evt);
            }
        });
        getContentPane().add(encryptData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 149, -1));

        decryptData.setText("Username");
        decryptData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptDataActionPerformed(evt);
            }
        });
        getContentPane().add(decryptData, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 36, 149, -1));

        encryptKey.setText("Key");
        getContentPane().add(encryptKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 149, -1));

        decryptKey.setText("Key");
        decryptKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptKeyActionPerformed(evt);
            }
        });
        getContentPane().add(decryptKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 98, 149, -1));

        encrypt.setText("Enter");
        getContentPane().add(encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 194, -1, -1));

        decrypt.setText("View");
        getContentPane().add(decrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 129, -1, -1));

        dePass.setText("Password");
        getContentPane().add(dePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 67, 149, -1));

        enPass.setText("Password");
        getContentPane().add(enPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 149, -1));

        credit.setText("Credit Card");
        getContentPane().add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 149, -1));

        social.setText("Social Security");
        social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialActionPerformed(evt);
            }
        });
        getContentPane().add(social, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 149, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 15, 110));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 330, 110));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decryptDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decryptDataActionPerformed

    private void decryptKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decryptKeyActionPerformed

    private void encryptDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptDataActionPerformed

    private void socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncrypterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncrypterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncrypterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncrypterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncrypterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField credit;
    public javax.swing.JTextField dePass;
    public javax.swing.JButton decrypt;
    public javax.swing.JTextField decryptData;
    public javax.swing.JTextField decryptKey;
    public javax.swing.JTextField enPass;
    public javax.swing.JButton encrypt;
    public javax.swing.JTextField encryptData;
    public javax.swing.JTextField encryptKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea output;
    public javax.swing.JTextField social;
    // End of variables declaration//GEN-END:variables
}
